require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.7.6

  Exclude:
    - 'bin/*'
    - 'tmp/*'
    - 'spec/spec_helper.rb'
    - 'spec/dummy/config.ru'
    - 'spec/dummy/bin/**/*'
    - 'spec/dummy/config/**/*'
    - 'spec/dummy/db/**/*'
    - 'spec/dummy/tmp/**/*'

  NewCops: enable
